apiVersion: v1
kind: ConfigMap
metadata:
  name: kube2iam-access
data:
  # The following is a list of applications that are allowed to assume the role via kube2iam and the annotations
  # The format is as follows:
  # <namespace>: [<role-arn>, <role-arn>, ...] OR ['*']
  allowFor: |
    'some-namespace':
      - arn:aws:iam::000000000000:role/Role_Name
