apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  wsp.io/part-of: wsp-cluster-configuration
  wsp.io/cluster-name: ${CLUSTER_NAME}

namespace: wsp-ns

resources:
  - sa.wsp-cd.yaml
  - secret.wsp-cd-token.yaml
  - cm.kube2iam-access.yaml
