apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wsp-sync-dev-cluster-infra
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-delete
#    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ] # ref: https://pkg.go.dev/text/template#Template.Option
  generators:
    - git:
        # repoURL: https://git.plesk.tech/scm/wsp/wsp-cluster-configuration.git
        repoURL: https://github.com/wsp-for-aws/wsp-cluster-configuration.git
        revision: master
        directories:
          - path: clusters/dev/cluster-wide
          - path: clusters/dev/namespaces/*
  template:
    metadata:
      name: '{{ if gt (len .path.segments) 3 }}{{index .path.segments 3}}-to{{ else }}clusters-wide-resources-for{{ end }}-{{index .path.segments 1}}'
      labels:
        wsp.io/application-name: '{{.path.basename}}'
        wsp.io/environment: '{{index .path.segments 1}}'
    spec:
      project: default
      source:
        # repoURL: https://git.plesk.tech/scm/wsp/wsp-cluster-configuration.git
        repoURL: https://github.com/wsp-for-aws/wsp-cluster-configuration.git
        targetRevision: master
        path: '{{ .path.path }}'
      destination:
        name: '{{ index .path.segments 1 }}'
        namespace: '{{ if gt (len .path.segments) 3 }}{{index .path.segments 3}}{{ else }}{{ end }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
