apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wsp-ns-to-dev
  namespace: argocd
spec:
  project: default
  source:
    # repoURL: https://git.plesk.tech/scm/wsp/wsp-cluster-configuration.git
    repoURL: https://github.com/wsp-for-aws/wsp-cluster-configuration.git
    targetRevision: master
    path: 'clusters/dev/namespaces/wsp-ns'
  destination:
    name: 'dev'
    namespace: 'wsp-ns'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
