apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wsp-sync-infra-per-ns
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://git.plesk.tech/scm/wsp/wsp-clusters-infra.git
        revision: kustomize
        directories:
          - path: clusters/dev/namespaces/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://git.plesk.tech/scm/wsp/wsp-clusters-infra.git
        targetRevision: kustomize
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true