apiVersion: v1
kind: Config
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server:  https://192.168.49.2:8443
    name: dev.wsp

contexts:
  - context:
      cluster: dev.wsp
      user: oidc-dev
    name: oidc@dev.wsp

current-context: oidc@dev.wsp
users:
  - name: oidc-dev
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://dev-dex.k8s-staging.plesk.tech
          - --oidc-client-id=kubelogin
          - --oidc-extra-scope="openid profile email groups"
        command: kubectl
