apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-all-clusters
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.plesk.tech/scm/wsp/wsp-clusters-infra.git
    targetRevision: kustomize
    path: 'clusters/'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
