apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wsp-sync-appsets-per-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.plesk.tech/scm/wsp/wsp-clusters-infra.git
    revision: kustomize
    path: 'clusters/*/application-set.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
