apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wsp-ns-viewer
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps", "pods", "pods/log", "services", "endpointslices", "endpoints", "events" ]
    verbs: [ "get", "list", "watch", "bind" ]

  - apiGroups: [ "batch" ]
    resources: [ "jobs", "cronjobs" ]
    verbs: [ "get", "list", "watch", "bind" ]

  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list", "watch", "bind" ]

  - apiGroups: [ "apps" ]
    resources: [ "deployments", "replicasets", "statefulsets" ]
    verbs: [ "get", "list", "watch", "bind" ]

  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "get", "list", "watch", "bind" ]
