apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  wsp.io/part-of: wsp-cluster-configuration
  wsp.io/cluster-name: ${CLUSTER_NAME}

resources:
  - kyverno-policies/
  - ccnp.core-dns-ingress.yaml
  - ccnp.core-dns-egress.yaml
  - cr.wsp-admin.yaml
  - cr.wsp-cd-default.yaml
  - cr.wsp-viewer.yaml
