apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  wsp.io/part-of: wsp-cluster-configuration
  wsp.io/cluster-name: dev

namespace: aws-client-app

resources:
  - ../../defaults/
  - deployment.app.yaml
