apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  wsp.io/part-of: wsp-cluster-configuration
  wsp.io/cluster-name: dev

namespace: wsp-ns

resources:
  - ns.wsp-ns.yaml
  - sa.wsp-cd.yaml
  - secret.wsp-cd-token.yaml
  - cm.kube2iam-access.yaml
#  - pvc.test.yaml
