apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wsp-cd
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps", "pods", "pods/log", "services", "endpointslices", "endpoints", "events" ]
    verbs: [ "*" ]

  - apiGroups: [ "batch" ]
    resources: [ "jobs", "cronjobs" ]
    verbs: [ "*" ]

  - apiGroups: [ "apps" ]
    resources: [ "deployments", "replicasets", "statefulsets" ]
    verbs: [ "*" ]

  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "*" ]

  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "list", "watch", "create", "update", "delete" ]

  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]

  - apiGroups: [ "policy" ]
    resources: [ "podsecuritypolicies" ]
    verbs: [ "use" ]
