apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wsp-dev-configuration
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ missingkey=error ] # ref: https://pkg.go.dev/text/template#Template.Option
  syncPolicy:
    applicationsSync: create-delete
  generators:
    - matrix:
        generators:
          - clusters:
              values:
                # WA:
                # `.metadata.annotations` has map[string]string type, but go functions expect map[string]interface{}.
                # `toYaml .metadata.annotations | fromYaml` allows us to make such a conversion.
                repo_url: '{{ toYaml .metadata.annotations | fromYaml | dig "wsp-cluster-configuration/repo-url" "https://git.plesk.tech/scm/wsp/wsp-cluster-configuration.git" }}'
                branch: '{{ toYaml .metadata.annotations | fromYaml | dig "wsp-cluster-configuration/branch" "master" }}'
            selector:
              matchExpressions:
                - key: name
                  operator: In
                  values:
                    - wsp-dev

          - git:
              repoURL: '{{ .values.repo_url }}'
              revision: '{{ .values.branch }}'
              directories:
                - path: 'clusters/{{ .name }}/cluster-wide'
                - path: 'clusters/{{ .name }}/namespaces/application/*'
                - path: 'clusters/{{ .name }}/namespaces/system/*'
  template:
    metadata:
      name: '{{ list .path.basename "-configuration." ( index .path.segments 1 ) | join "" | slugify 63 }}'
      labels:
        wsp-cluster-configuration/type: '{{ if gt (len .path.segments) 3 }}{{ index .path.segments 3 }}{{ else }}{{ .path.basename }}{{ end }}'
    #  annotations:
    #    link.argocd.argoproj.io/external-link: https://grafana.monitoring/namespace/dashboard
    spec:
      project: default
      source:
        repoURL: '{{ .values.repo_url }}'
        targetRevision: '{{ .values.branch }}'
        path: '{{ .path.path }}'
      destination:
        name: '{{ index .path.segments 1 }}'
        namespace: '{{ if eq (len .path.segments) 3 }}{{ else }}{{ index .path.segments 4 }}{{ end }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=false
          - FailOnSharedResource=true
  templatePatch: |
    spec:
      info:
        - name: Description
        {{- if eq (len .path.segments) 3 }}
          value: 'Provides the cluster-wide configuration.'
        {{- else if eq (index .path.segments 3) "system" }}
          value: 'Provides the configuration for "{{ index .path.segments 4 }}" namespace.'
        {{- else }}
          value: 'Provides administrative resources for "{{ index .path.segments 4 }}" application namespace.'
        {{- end }}
        - name: Source
          value: 'https://git.plesk.tech/projects/WSP/repos/wsp-cluster-configuration/browse/{{ .values.repo_url }}?at=refs%2Fheads%2F{{ .values.branch }}'
