apiVersion: v1
kind: ResourceQuota
metadata:
  name: wsp
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    count/pods: "20"
    count/services: "10"
    count/deployments.apps: "10"
    count/jobs.batch: "20"
    count/cronjobs.batch: "10"
    count/persistentvolumeclaims: "3"
