apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wsp-ns-admin
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "pods/log", "services", "endpoints", "configmaps" ]
    verbs: [ "*" ]

  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]

  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "*" ]

  - apiGroups: [ "extensions" ]
    resources: [ "ingresses" ]
    verbs: [ "*" ]
