apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  wsp.io/part-of: wsp-cluster-configuration
  wsp.io/cluster-name: dev

namespace: typical-app

resources:
  - ../../defaults/

patches:
  - target:
      version: v1
      kind: ResourceQuota
      name: wsp
    patch: |-
      - op: replace
        path: /spec/hard/requests.cpu
        value: "2"
      - op: replace
        path: /spec/hard/limits.cpu
        value: "2"