apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  wsp.io/part-of: wsp-cluster-configuration

resources:
  - ns.target.yaml
  - cnp.allow-traffic-within-namespace.yaml
  - rolebinding.wsp-cd.yaml
  - quota.ns-limits.yaml
