apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  ## Source of the several policies: https://kyverno.io/policies/
  - add-default-requests.yaml
  - no-loadbalancer-service.yaml
  - restrict-ingress-wildcard.yaml
  - restrict-kube2iam-annotations.yaml
  - unique-external-dns.yaml
  - unique-ingress-host.yaml
  - validate-probes.yaml
