apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  wsp.io/part-of: wsp-cluster-configuration
  wsp.io/cluster-name: dev

resources:
  - ns.target.yaml
  - cnp.allow-traffic-within-namespace.yaml
  - rq.wsp.yaml
  - rb.wsp-cd.yaml
