apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wsp-sync-${CLUSTER_NAME}-cluster-infra
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true # ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ] # ref: https://pkg.go.dev/text/template#Template.Option
  generators:
    - git:
        # repoURL: https://git.plesk.tech/scm/wsp/wsp-cluster-configuration.git
        repoURL: https://github.com/wsp-for-aws/wsp-cluster-configuration.git
        revision: master
        directories:
          - path: clusters/${CLUSTER_NAME}/namespaces/*
          - path: clusters/${CLUSTER_NAME}/cluster-wide
  template:
    metadata:
      name: 'cluster-{{index .path.segments 1}}-ns-{{.path.basename}}'
      labels:
        wsp.io/application-name: '{{.path.basename}}'
        wsp.io/environment: '{{index .path.segments 1}}'
    spec:
      project: default
      source:
        # repoURL: https://git.plesk.tech/scm/wsp/wsp-cluster-configuration.git
        repoURL: https://github.com/wsp-for-aws/wsp-cluster-configuration.git
        targetRevision: master
        path: '{{.path.path}}'
      destination:
        name: '{{index .path.segments 1}}'
        namespace: ''
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=false
          - FailOnSharedResource=true
