apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ${CLUSTER_NAME}-configuration
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ] # ref: https://pkg.go.dev/text/template#Template.Option
  syncPolicy:
    applicationsSync: create-delete
  generators:
    - matrix:
        generators:
          - clusters:
              values:
                # WA:
                # `.metadata.annotations` has map[string]string type, but go functions expect map[string]interface{}.
                # `toYaml .metadata.annotations | fromYaml` allows us to make such a conversion.
                repo_url: '{{ toYaml .metadata.annotations | fromYaml | dig "wsp-cluster-configuration/repo-url" "https://git.plesk.tech/scm/wsp/wsp-cluster-configuration.git" }}'
                revision: '{{ toYaml .metadata.annotations | fromYaml | dig "wsp-cluster-configuration/revision" "master" }}'
            selector:
              matchExpressions:
                - key: name
                  operator: In
                  values:
                    - ${CLUSTER_NAME}

          - git:
              repoURL: "{{ .values.repo_url }}"
              revision: "{{ .values.revision }}"
              directories:
                - path: "clusters/{{ .name }}/cluster-wide"
                - path: "clusters/{{ .name }}/namespaces/*"
  template:
    metadata:
      name: '{{ if gt (len .path.segments) 3 }}{{index .path.segments 3}}-to{{ else }}clusters-wide-resources-for{{ end }}-{{index .path.segments 1}}'
      labels:
        wsp.io/application: '{{ .path.basename }}'
        wsp.io/destination: '{{ index .path.segments 1 }}'
    spec:
      project: default
      source:
        repoURL: "{{ .values.repo_url }}"
        targetRevision: "{{ .values.revision }}"
        path: '{{ .path.path }}'
      destination:
        name: '{{ index .path.segments 1 }}'
        namespace: '{{ if gt (len .path.segments) 3 }}{{index .path.segments 3}}{{ else }}{{ end }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=false
          - FailOnSharedResource=true
