apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wsp-${CLUSTER_NAME}-configuration
  namespace: argocd
spec:
  syncPolicy:
    # ApplicationSet will not cascade delete resources when the application is deleted
    # ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ] # ref: https://pkg.go.dev/text/template#Template.Option
  generators:
    - git:
        repoURL: https://git.plesk.tech/scm/wsp/wsp-cluster-configuration.git
        revision: master
        directories:
          - path: clusters/${CLUSTER_NAME}/cluster-wide
          - path: clusters/${CLUSTER_NAME}/namespaces/*
  template:
    metadata:
      name: '{{ index .path.segments 1 }}-ns-{{ .path.basename }}'
      labels:
        wsp.io/application: '{{ .path.basename }}'
        wsp.io/destination: '{{ index .path.segments 1 }}'
    spec:
      project: default
      source:
        repoURL: https://git.plesk.tech/scm/wsp/wsp-cluster-configuration.git
        targetRevision: master
        path: '{{ .path.path }}'
      destination:
        name: '{{ index .path.segments 1 }}'
        namespace: ''
      syncPolicy:
        automated:
          # Application will not destroy resources that are not in the Git repository
          prune: false
          # Application will self-heal if the live state does not match the desired state
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
