apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wsp-${CLUSTER_NAME}-configuration
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ] # ref: https://pkg.go.dev/text/template#Template.Option
  syncPolicy:
    applicationsSync: create-delete
  generators:
    - git:
        repoURL: https://git.plesk.tech/scm/wsp/wsp-cluster-configuration.git
        revision: master
        directories:
          - path: clusters/${CLUSTER_NAME}/cluster-wide
          - path: clusters/${CLUSTER_NAME}/namespaces/*
  template:
    metadata:
      name: '{{ if gt (len .path.segments) 3 }}{{index .path.segments 3}}-to{{ else }}clusters-wide-resources-for{{ end }}-{{index .path.segments 1}}'
      labels:
        wsp.io/application: '{{ .path.basename }}'
        wsp.io/destination: '{{ index .path.segments 1 }}'
    spec:
      project: default
      source:
        repoURL: https://git.plesk.tech/scm/wsp/wsp-cluster-configuration.git
        targetRevision: master
        path: '{{ .path.path }}'
      destination:
        name: '{{ index .path.segments 1 }}'
        namespace: '{{ if gt (len .path.segments) 3 }}{{index .path.segments 3}}{{ else }}{{ end }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=false
          - FailOnSharedResource=true
