apiVersion: v1
kind: Secret
metadata:
  name: long-live-token-by-nefimov
  namespace: default
  annotations:
    kubernetes.io/service-account.name: user-nefimov
type: kubernetes.io/service-account-token
